# Generated by Django 4.2.1 on 2023-05-16 18:12

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network_id', models.CharField(max_length=100, unique=True, verbose_name='NetworkID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('gbfs_href', models.URLField(blank=True, null=True, verbose_name='GBFS_Href')),
                ('href', models.CharField(max_length=255, verbose_name='Href')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ManyToManyField(blank=True, to='network.company', verbose_name='network_company')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Name')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='last_updated')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Stations',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('free_bikes', models.SmallIntegerField(verbose_name='Free Bikes')),
                ('empty_slots', models.SmallIntegerField(verbose_name='Empty Slots')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='Longitude')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('network', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='network_stations', to='network.network')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=2, verbose_name='Country')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='Longitude')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('network', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='network_location', to='network.network')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Extra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField(verbose_name='UID')),
                ('altitude', models.SmallIntegerField(blank=True, null=True)),
                ('ebikes', models.SmallIntegerField(default=0)),
                ('has_ebikes', models.BooleanField(default=False)),
                ('normal_bikes', models.SmallIntegerField(default=0)),
                ('address', models.CharField(max_length=255)),
                ('payment_terminal', models.BooleanField(default=False)),
                ('slots', models.SmallIntegerField(default=0)),
                ('returning', models.SmallIntegerField(default=0)),
                ('renting', models.SmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='last_updated')),
                ('payment', models.ManyToManyField(blank=True, related_name='payment_extra', to='network.payment', verbose_name='payment_extra')),
                ('stations', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stations_extra', to='network.stations')),
            ],
        ),
    ]
