# Generated by Django 4.2.1 on 2023-05-17 14:21

from django.db import migrations, models
import django_jsonform.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Snifa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.CharField(max_length=50, verbose_name='File')),
                ('auditable_unit', django_jsonform.models.fields.ArrayField(base_field=models.CharField(max_length=20, verbose_name='Auditable Unit'), size=None)),
                ('auditable_unit_url', django_jsonform.models.fields.ArrayField(base_field=models.URLField(blank=True, null=True, verbose_name='Auditable Unit URL'), size=None)),
                ('company_name', django_jsonform.models.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Company Name'), size=None)),
                ('category', models.CharField(blank=True, max_length=255, null=True, verbose_name='Category')),
                ('region', models.CharField(max_length=100, verbose_name='Region')),
                ('state', models.CharField(max_length=100, verbose_name='State')),
                ('detail_url', models.URLField(blank=True, null=True, verbose_name='Detail URL')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
